### ISSUE TITLE
Change Management - Snapshots

### ISSUE THREAD

**Issue by hutger** [k8debug/vpk#3]
Hi There, 

First and foremost, my compliments for the awesome tool. The idea of snapshots is what I was looking for.

I have now the app running and I'm wondering if there's a way to apply the snapshots as input for a Change Management analysis. 

I mean... I would like to see the changes between two snapshots taken in different moments. Is this feature implemented?

Maybe this is an already a present feature which I've overlooked. My apologies if this is the case.

/Hutger

**Comment by k8debug** [comment]
Hutger,
There currently is no feature to compare snapshots.  I've discussed such a feature with a couple of folks.  Thus far what has been discussed at a high level is:

Compare at resource name level - This would include all resource types to determine if any resource names do not exist in both snapshot.

Compare at resource definition level - Compare only the resource definition without the ManagedFields or Status sections.  Check the following fields:  creationTimestamp, resourceVersion, and uid to determine any differences.

List output by namespace and by cluster level if non-namespace resource.

There is possible consideration to include actually use the Status section and check for any difference in status but no agreement on that at this time.

Planning is underway for the next set of features and this request will be under consideration.

As of today the only feature that has been agreed to is the inclusion of graphical view of the cluster nodes that includes Pods and networking.

Thanks again,

**Comment by hutger** [comment]
Hi there, thanks for your feedback and for taking the suggestion into consideration. I'll stay tuned with the upcoming versions then. Cheers.

**Comment by k8debug** [comment]
Hutger,
A new compare feature has been added to VpK.  The only way to update VpK is
to get the latest code in github and perform a new install.

Hope this feature is of use to you and others.

VpK Team
