### ISSUE TITLE
Xref definition or changes should inform the user the snapshot should be re-parsed 

### ISSUE THREAD

**Issue by k8debug** [k8debug/vpk#8]
If X-Reference maintenance is performed causing changes to existing xRef definitions the user should be informed to re-parse the connected snapshot, if one is connected.  This insures the user will see the latest xref data.

**Comment by vjlandon** [comment]
Enhancement was added.  Once a user edits or deletes any of the xRef definitions an alert message is shown on the first page that overlays the tabs.  The message must be closed before any tab can be selected.  This approach forces an action by the user before they are allowed to continue.  This enhancement was included as part of the Compare Snapshot pull request.
