### ISSUE TITLE
chgP2 function is missing

### ISSUE THREAD

**Issue by k8debug** [k8debug/vpk#9]
Function chgP2 is missing and causes a stack error when using url: localhost:4200/dumpobj/<name>.  The value 
<name> is the object name that is to be shown from global memory in the 'vpk' object.

**Comment by dweilert** [comment]
function chgP2 was added to the utl.js module.  The fix was incorporated with the Compare Snapshot pull request.

**Comment by k8debug** [comment]
The fix was tested and resolved the issue.
